### ISSUE TITLE
Conexão do banco exposta

### ISSUE THREAD

**Issue by mrbrunelli** [ayslanPurunga/crud_nest_heroku#1]
Evite deixar informações sensíveis no código, trabalhe sempre com variáveis de ambiente. Use também o .gitignore para evitar versionamento de arquivos sensíveis para o repositório.
No NestJS é muito fácil trabalhar com arquivos .env, [Aqui na documentação](https://docs.nestjs.com/techniques/configuration) tem uma seção explicando como fazer isso.

https://github.com/ayslanPurunga/crud_nest_heroku/blob/a2aaca6bd95a5e57424b3b6358913f5e77ad2b4f/src/app.module.ts#L1-L17

**Comment by ayslanPurunga** [comment]
Resolvido, criado variaveis de ambiente e feito conexão com o banco de dados.
